"""initial_schema

Revision ID: 240de0a4f0b8
Revises: 
Create Date: 2026-04-01 05:39:12.119681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '240de0a4f0b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ai_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('perspective_threshold', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('areas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('citizens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=True),
    sa.Column('consent_given_at', sa.DateTime(), nullable=True),
    sa.Column('consent_version', sa.Integer(), nullable=False),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('temp_password_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizens_email'), 'citizens', ['email'], unique=True)
    op.create_table('forloeb',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('allow_citizen_questions', sa.Boolean(), nullable=True),
    sa.Column('citizen_question_requires_approval', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('moderation_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=True),
    sa.Column('pattern', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('citizen_id', sa.String(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_version', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_logs_citizen_id'), 'consent_logs', ['citizen_id'], unique=False)
    op.create_table('password_reset_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('admin_user_id', sa.String(), nullable=False),
    sa.Column('target_citizen_id', sa.String(), nullable=False),
    sa.Column('reset_at', sa.DateTime(), nullable=True),
    sa.Column('temp_password_expires', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['target_citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_log_target_citizen_id'), 'password_reset_log', ['target_citizen_id'], unique=False)
    op.create_table('response_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('citizen_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('citizen_id')
    )
    op.create_table('themes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('forloeb_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['forloeb_id'], ['forloeb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_theme_forloeb_id', 'themes', ['forloeb_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('theme_id', sa.String(), nullable=True),
    sa.Column('forloeb_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('allow_followup', sa.Boolean(), nullable=True),
    sa.Column('followup_prompt', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_citizen_submitted', sa.Boolean(), nullable=True),
    sa.Column('submitted_by_citizen_id', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['forloeb_id'], ['forloeb.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_citizen_id'], ['citizens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_forloeb_id', 'questions', ['forloeb_id'], unique=False)
    op.create_index('ix_question_theme_id', 'questions', ['theme_id'], unique=False)
    op.create_table('analysis_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=True),
    sa.Column('theme_id', sa.String(), nullable=True),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('response_count_at_generation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_cache_question_id', 'analysis_cache', ['question_id'], unique=False)
    op.create_index('ix_analysis_cache_theme_id', 'analysis_cache', ['theme_id'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('citizen_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('response_type', sa.String(length=20), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('audio_file_path', sa.String(length=500), nullable=True),
    sa.Column('media_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_followup', sa.Boolean(), nullable=True),
    sa.Column('parent_response_id', sa.String(), nullable=True),
    sa.Column('followup_question_text', sa.Text(), nullable=True),
    sa.Column('is_excluded', sa.Boolean(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_response_id'], ['responses.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_response_citizen_id', 'responses', ['citizen_id'], unique=False)
    op.create_index('ix_response_created_at', 'responses', ['created_at'], unique=False)
    op.create_index('ix_response_question_id', 'responses', ['question_id'], unique=False)
    op.create_index(op.f('ix_responses_is_excluded'), 'responses', ['is_excluded'], unique=False)
    op.create_index(op.f('ix_responses_is_flagged'), 'responses', ['is_flagged'], unique=False)
    op.create_index(op.f('ix_responses_session_id'), 'responses', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responses_session_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_is_flagged'), table_name='responses')
    op.drop_index(op.f('ix_responses_is_excluded'), table_name='responses')
    op.drop_index('ix_response_question_id', table_name='responses')
    op.drop_index('ix_response_created_at', table_name='responses')
    op.drop_index('ix_response_citizen_id', table_name='responses')
    op.drop_table('responses')
    op.drop_index('ix_analysis_cache_theme_id', table_name='analysis_cache')
    op.drop_index('ix_analysis_cache_question_id', table_name='analysis_cache')
    op.drop_table('analysis_cache')
    op.drop_index('ix_question_theme_id', table_name='questions')
    op.drop_index('ix_question_forloeb_id', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_theme_forloeb_id', table_name='themes')
    op.drop_table('themes')
    op.drop_table('response_metadata')
    op.drop_index(op.f('ix_password_reset_log_target_citizen_id'), table_name='password_reset_log')
    op.drop_table('password_reset_log')
    op.drop_index(op.f('ix_consent_logs_citizen_id'), table_name='consent_logs')
    op.drop_table('consent_logs')
    op.drop_table('moderation_rules')
    op.drop_table('forloeb')
    op.drop_index(op.f('ix_citizens_email'), table_name='citizens')
    op.drop_table('citizens')
    op.drop_table('areas')
    op.drop_table('ai_settings')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
